[package]
name = "repak-py"
version = "0.2.3"
edition = "2024"
license = "MIT"
publish = false

[workspace]
members = ["vendor/oodle_loader"]

[lib]
name = "_repak"
crate-type = ["cdylib"]

[dependencies]
aes = "0.8"
base64 = "0.23"
hex = "0.4"
oodle_loader = { path = "vendor/oodle_loader" }
pyo3 = { version = "0.29", features = ["abi3-py310", "extension-module"] }
repak = { git = "https://github.com/trumank/repak.git", tag = "v0.2.3", features = [
    "oodle",
] }

[patch."https://github.com/trumank/repak.git"]
oodle_loader = { path = "vendor/oodle_loader" }

[profile.release]
lto = "thin"
strip = true
